// Code generated by Slice Machine. DO NOT EDIT.

import AboutUsSection from './AboutUsSection/index.svelte';
import Bento from './Bento/index.svelte';
import BentoStack from './BentoStack/index.svelte';
import CaseStudies from './CaseStudies/index.svelte';
import Categories from './Categories/index.svelte';
import ContactUsSection from './ContactUsSection/index.svelte';
import FaqSection from './FaqSection/index.svelte';
import Hero from './Hero/index.svelte';
import InfoProducts from './InfoProducts/index.svelte';
import OrderSummarySection from './OrderSummarySection/index.svelte';
import PinCards from './PinCards/index.svelte';
import ProductSection from './ProductSection/index.svelte';
import Products from './Products/index.svelte';
import PromoCards from './PromoCards/index.svelte';
import Reviews from './Reviews/index.svelte';
import RichText from './RichText/index.svelte';
import TermsAndConditionsSection from './TermsAndConditionsSection/index.svelte';

export const components = {
	about_us_section: AboutUsSection,
	bento: Bento,
	bento_stack: BentoStack,
	case_studies: CaseStudies,
	categories: Categories,
	contact_us_section: ContactUsSection,
	faq_section: FaqSection,
	hero: Hero,
	info_products: InfoProducts,
	order_summary_section: OrderSummarySection,
	pin_cards: PinCards,
	product_section: ProductSection,
	products: Products,
	promo_cards: PromoCards,
	reviews: Reviews,
	rich_text: RichText,
	terms_and_conditions_section: TermsAndConditionsSection
};
