// Code generated by Slice Machine. DO NOT EDIT.

import Bento from './Bento/index.svelte';
import BentoStack from './BentoStack/index.svelte';
import Hero from './Hero/index.svelte';
import RichText from './RichText/index.svelte';

export const components = {
	bento: Bento,
	bento_stack: BentoStack,
	hero: Hero,
	rich_text: RichText
};
